####################################################################################################
############################## Сервис оповещений ####################################################
####################################################################################################

@AToken={{login.response.body.tokens.accessToken}}

# Аутентификация пользователя
# @name login
POST http://localhost:4000/fitfriends/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "john@user.com",
  "password": "123456"
}

###
# Получение списка оповещений
GET  http://localhost:4000/fitfriends/alerts HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{AToken}}

###
# Удаление оповещения
DELETE  http://localhost:4000/fitfriends/alerts/4 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{AToken}}
