@AToken={{login.response.body.accessToken}}

# Аутентификация пользователя
# @name login
POST http://localhost:4000/fitfriends/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "shara@user.com",
  "password": "123456"
}

###

# Добавление нового друга
POST http://localhost:4000/fitfriends/friends/6 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{AToken}}

###

#Получение списка друзей
GET  http://localhost:4000/fitfriends/friends HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{AToken}}

###

# Удаление друга
DELETE  http://localhost:4000/fitfriends/friends/6 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{AToken}}

###

# Аутентификация пользователя
# @name login
POST http://localhost:4000/fitfriends/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "rob@trainer.com",
  "password": "123456"
}

# Получение списка пользователей, которые добавили тренера в друзья
###

GET  http://localhost:4000/fitfriends/friends/trainer HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{AToken}}