version: '3.9'
services:
  fitfriends.postgres:
    image: postgres:latest
    container_name: fitfriends.postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - fitfriends.publication:/var/lib/postgresql/data

    healthcheck:
      test:
        ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d {POSTGRES_PASSWORD}']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

    networks:
      - fitfriends

  fitfriends.pgadmin:
    image: dpage/pgadmin4:latest
    container_name: fitfriends.pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - 8081:80
    depends_on:
      - fitfriends.postgres
    networks:
      - fitfriends

  fitfriends.notify.fakesmtp:
    image: gessnerfl/fake-smtp-server:latest
    container_name: 'fitfriends.notify.fakesmtp'
    hostname: 'fitfriends.notify.fakesmtp'
    ports:
      - '8025:8025'
      - '1083:8080'

  fitfriends.notify.rabbitmq:
    image: rabbitmq:3.13-management
    container_name: fitfriends.notify.rabbitmq

    ports:
      - '1088:15672'
      - '5672:5672'

    environment:
      RABBITMQ_DEFAULT_USER: ${RABBIT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBIT_PASSWORD}

    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  fitfriends.publication:

networks:
  fitfriends:
    driver: bridge
