####################################################################################################
############################## Сервис отзывов ######################################################
####################################################################################################

# Создание нового пользователя
# @name register
POST http://localhost:4000/fitfriends/reviews HTTP/1.1
Content-Type: application/json

{
  "author": 11,
  "training": 22,
  "grade": 3,
  "text": "Но диаграммы связей набирают популярность среди определенных слоев населения, а значит, должны быть ограничены исключительно образом мышления."
}
