####################################################################################################
############################## Сервис персональных тренировок #######################################
####################################################################################################

@AToken={{login.response.body.tokens.accessToken}}

# Аутентификация пользователя
# @name login
POST http://localhost:4000/fitfriends/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "john@user.com",
  "password": "123456"
}

###
# Заявка на персональную тренировку
POST http://localhost:4000/fitfriends/personal-trainings/2 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{AToken}}

{
  "status":"на рассмотрении"
}

################################################################################

# Аутентификация пользователя
# @name login
POST http://localhost:4000/fitfriends/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "rob@user.com",
  "password": "123456"
}

###
#Обновление статуса заявки на персональную тренировку
PATCH http://localhost:4000/fitfriends/personal-trainings/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{AToken}}

{
  "status":"принят"
}

################################################################################
###
# Аутентификация пользователя
# @name login
POST http://localhost:4000/fitfriends/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "katrin@trainer.com",
  "password": "123456"
}

###
#Обновление статуса заявки на персональную тренировку
PATCH http://localhost:4000/fitfriends/personal-trainings/5 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{AToken}}

{
  "status":"отклонён"
}


###
#Получение персональных тренировок
GET http://localhost:4000/fitfriends/personal-trainings HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{AToken}}

