####################################################################################################
############################## Сервис заказов пользователя ##########################################
####################################################################################################
#
#Пользователи с ролью пользователь john@user.com, shara@user.com, mikle@user.com
#
#Пароль у всех 123456
#
#training_id  1,2,3,4,5,6,7,8,9


@AToken={{login.response.body.accessToken}}

####################################################################################################
# Аутентификация пользователя john@user.com
# @name login
POST http://localhost:4000/fitfriends/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "john@user.com",
  "password": "123456"
}

###
# Создание нового заказа
POST http://localhost:4000/fitfriends/orders/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{AToken}}

{
  "type": "абонемент",
  "price": 150,
  "amount": 5,
  "pay": "mir"
}

###

# Создание нового заказа
POST http://localhost:4000/fitfriends/orders/7 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{AToken}}

{
  "type": "абонемент",
  "price": 150,
  "amount": 3,
  "pay": "mir"
}

###

# Создание нового заказа
POST http://localhost:4000/fitfriends/orders/13 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{AToken}}

{
  "type": "абонемент",
  "price": 500,
  "amount": 1,
  "pay": "mir"
}

###
###################################################################################################
# Аутентификация пользователя shara@user.com
# @name login
POST http://localhost:4000/fitfriends/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "shara@user.com",
  "password": "123456"
}

###

# Создание нового заказа
POST http://localhost:4000/fitfriends/orders/2 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{AToken}}

{
  "type": "абонемент",
  "price": 950,
  "amount": 5,
  "pay": "visa"
}

###

# Создание нового заказа
POST http://localhost:4000/fitfriends/orders/8 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{AToken}}

{
  "type": "абонемент",
  "price": 500,
  "amount":12,
  "pay": "visa"
}

###

# Создание нового заказа
POST http://localhost:4000/fitfriends/orders/14 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{AToken}}

{
  "type": "абонемент",
  "price": 1100,
  "amount": 10,
  "pay": "visa"
}

###
###################################################################################################
# Аутентификация пользователя mikle@user.com
# @name login
POST http://localhost:4000/fitfriends/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "mikle@user.com",
  "password": "123456"
}

###

# Создание нового заказа
POST http://localhost:4000/fitfriends/orders/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{AToken}}

{
  "type": "абонемент",
  "price": 100,
  "amount": 25,
  "pay": "umoney"
}

###

# Создание нового заказа
POST http://localhost:4000/fitfriends/orders/9 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{AToken}}

{
  "type": "абонемент",
  "price": 1350,
  "amount": 3,
  "pay": "umoney"
}

###

# Создание нового заказа
POST http://localhost:4000/fitfriends/orders/14 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{AToken}}

{
  "type": "абонемент",
  "price": 650,
  "amount": 12,
  "pay": "umoney"
}

###

# Создание нового заказа
POST http://localhost:4000/fitfriends/orders/13 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{AToken}}

{
  "type": "абонемент",
  "price": 450,
  "amount": 4,
  "pay": "umoney"
}
####################################################################################################
# Аутентификация пользователя evgeny@user.com
# @name login
POST http://localhost:4000/fitfriends/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "evgeny@user.com",
  "password": "123456"
}

###

# Создание нового заказа
POST http://localhost:4000/fitfriends/orders/2 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{AToken}}

{
  "type": "абонемент",
  "price": 1100,
  "amount": 5,
  "pay": "mir"
}

###

# Создание нового заказа
POST http://localhost:4000/fitfriends/orders/4 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{AToken}}

{
  "type": "абонемент",
  "price": 750,
  "amount": 3,
  "pay": "mir"
}

###

# Создание нового заказа
POST http://localhost:4000/fitfriends/orders/15 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{AToken}}

{
  "type": "абонемент",
  "price": 650,
  "amount": 3,
  "pay": "mir"
}

###

# Создание нового заказа
POST http://localhost:4000/fitfriends/orders/18 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{AToken}}

{
  "type": "абонемент",
  "price": 750,
  "amount": 4,
  "pay": "mir"
}

####################################################################################################
# Аутентификация пользователя valery@user.com
# @name login
POST http://localhost:4000/fitfriends/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "valery@user.com",
  "password": "123456"
}

###

# Создание нового заказа
POST http://localhost:4000/fitfriends/orders/3 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{AToken}}

{
  "type": "абонемент",
  "price": 1000,
  "amount": 15,
  "pay": "mir"
}

###

# Создание нового заказа
POST http://localhost:4000/fitfriends/orders/4 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{AToken}}

{
  "type": "абонемент",
  "price": 350,
  "amount": 13,
  "pay": "mir"
}

###

# Создание нового заказа
POST http://localhost:4000/fitfriends/orders/17 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{AToken}}

{
  "type": "абонемент",
  "price": 650,
  "amount": 21,
  "pay": "mir"
}

###

# Создание нового заказа
POST http://localhost:4000/fitfriends/orders/18 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{AToken}}

{
  "type": "абонемент",
  "price": 2500,
  "amount": 4,
  "pay": "mir"
}

####################################################################################################
# Аутентификация пользователя mickael@user.com
# @name login
POST http://localhost:4000/fitfriends/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "mickael@user.com",
  "password": "123456"
}

###

# Создание нового заказа
POST http://localhost:4000/fitfriends/orders/4 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{AToken}}

{
  "type": "абонемент",
  "price": 1300,
  "amount": 15,
  "pay": "mir"
}

###

# Создание нового заказа
POST http://localhost:4000/fitfriends/orders/7 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{AToken}}

{
  "type": "абонемент",
  "price": 350,
  "amount": 32,
  "pay": "mir"
}

###

# Создание нового заказа
POST http://localhost:4000/fitfriends/orders/11 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{AToken}}

{
  "type": "абонемент",
  "price": 650,
  "amount": 4,
  "pay": "mir"
}

###

# Создание нового заказа
POST http://localhost:4000/fitfriends/orders/17 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{AToken}}

{
  "type": "абонемент",
  "price": 2150,
  "amount": 4,
  "pay": "mir"
}

