@AToken={{login.response.body.accessToken}}

# Аутентификация пользователя
# @name login
POST http://localhost:4000/fitfriends/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "john@user.com",
  "password": "123456"
}

###

# Создание баланса
POST http://localhost:4000/fitfriends/balances HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{AToken}}

{
  "amount":3
}

###

# Получение баланса
GET  http://localhost:4000/fitfriends/balances HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{AToken}}


###

# Обновление баланса
PATCH  http://localhost:4000/fitfriends/balances HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{AToken}}

{
  "amount":1
}

